### ISSUE TITLE
can't run alpaca

### ISSUE THREAD

**Issue by Da5hes** [StetsonMathCS/alpaca#11]
Hi there,
I've tried to execute the commands from the documentation, but any command i execute results in the next warning:
Warning: /home/da5h/Downloads/alpaca/alpaca.pl:511:
	Singleton variables: [B,L,A]

nothing else is happening

**Comment by joshuaeckroth** [comment]
Hi Da5hes, I made a bunch of fixes on a private repo for a paper submission. I'll migrate those over in a couple days. Thanks for the interest.

**Comment by Da5hes** [comment]
@joshuaeckroth thanks, can't wait to try it out!

**Comment by joshuaeckroth** [comment]
Ok, have a look! Please make an issue if something doesn't work. Thanks!
